# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/liyongyi/Documents/IS590 PZ/othello_ai_solver/M.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QPainter, QColor, QFont
from PyQt5.QtWidgets import QApplication,QMainWindow,QDialog,QWidget
from PyQt5.QtCore import Qt

class Ui_Widget(QWidget):
    def setupUi(self,Widget):
        Widget.setObjectName("Widget")
        Widget.resize(649, 638)
        self.line = QtWidgets.QFrame(Widget)
        self.line.setEnabled(True)
        self.line.setGeometry(QtCore.QRect(30, 30, 591, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Widget)
        self.line_2.setEnabled(True)
        self.line_2.setGeometry(QtCore.QRect(30, 80, 591, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(Widget)
        self.line_3.setEnabled(True)
        self.line_3.setGeometry(QtCore.QRect(30, 130, 591, 20))
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(Widget)
        self.line_4.setEnabled(True)
        self.line_4.setGeometry(QtCore.QRect(30, 180, 591, 20))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(Widget)
        self.line_5.setEnabled(True)
        self.line_5.setGeometry(QtCore.QRect(30, 230, 591, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(Widget)
        self.line_6.setEnabled(True)
        self.line_6.setGeometry(QtCore.QRect(30, 280, 591, 20))
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.line_7 = QtWidgets.QFrame(Widget)
        self.line_7.setEnabled(True)
        self.line_7.setGeometry(QtCore.QRect(30, 480, 591, 20))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.line_8 = QtWidgets.QFrame(Widget)
        self.line_8.setEnabled(True)
        self.line_8.setGeometry(QtCore.QRect(30, 380, 591, 20))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.line_9 = QtWidgets.QFrame(Widget)
        self.line_9.setEnabled(True)
        self.line_9.setGeometry(QtCore.QRect(30, 330, 591, 20))
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.line_10 = QtWidgets.QFrame(Widget)
        self.line_10.setEnabled(True)
        self.line_10.setGeometry(QtCore.QRect(30, 430, 591, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.line_11 = QtWidgets.QFrame(Widget)
        self.line_11.setGeometry(QtCore.QRect(20, 40, 20, 451))
        self.line_11.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.line_12 = QtWidgets.QFrame(Widget)
        self.line_12.setGeometry(QtCore.QRect(85, 40, 20, 451))
        self.line_12.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.line_13 = QtWidgets.QFrame(Widget)
        self.line_13.setGeometry(QtCore.QRect(150, 40, 20, 451))
        self.line_13.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.line_14 = QtWidgets.QFrame(Widget)
        self.line_14.setGeometry(QtCore.QRect(410, 40, 20, 451))
        self.line_14.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_14.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_14.setObjectName("line_14")
        self.line_15 = QtWidgets.QFrame(Widget)
        self.line_15.setGeometry(QtCore.QRect(540, 40, 20, 451))
        self.line_15.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_15.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_15.setObjectName("line_15")
        self.line_16 = QtWidgets.QFrame(Widget)
        self.line_16.setGeometry(QtCore.QRect(610, 40, 20, 451))
        self.line_16.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_16.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_16.setObjectName("line_16")
        self.line_17 = QtWidgets.QFrame(Widget)
        self.line_17.setGeometry(QtCore.QRect(345, 40, 20, 451))
        self.line_17.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_17.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_17.setObjectName("line_17")
        self.line_18 = QtWidgets.QFrame(Widget)
        self.line_18.setGeometry(QtCore.QRect(215, 40, 20, 451))
        self.line_18.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_18.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_18.setObjectName("line_18")
        self.line_19 = QtWidgets.QFrame(Widget)
        self.line_19.setGeometry(QtCore.QRect(475, 40, 20, 451))
        self.line_19.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_19.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_19.setObjectName("line_19")
        self.line_20 = QtWidgets.QFrame(Widget)
        self.line_20.setGeometry(QtCore.QRect(280, 40, 20, 451))
        self.line_20.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_20.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_20.setObjectName("line_20")
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(10, 80, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Widget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 60, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Widget)
        self.label_3.setGeometry(QtCore.QRect(10, 180, 60, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Widget)
        self.label_4.setGeometry(QtCore.QRect(10, 230, 60, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Widget)
        self.label_5.setGeometry(QtCore.QRect(10, 280, 60, 16))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Widget)
        self.label_6.setGeometry(QtCore.QRect(10, 380, 60, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Widget)
        self.label_7.setGeometry(QtCore.QRect(10, 330, 60, 16))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Widget)
        self.label_8.setGeometry(QtCore.QRect(10, 430, 60, 16))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Widget)
        self.label_9.setGeometry(QtCore.QRect(90, 500, 60, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Widget)
        self.label_10.setGeometry(QtCore.QRect(285, 500, 60, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Widget)
        self.label_11.setGeometry(QtCore.QRect(155, 500, 60, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Widget)
        self.label_12.setGeometry(QtCore.QRect(545, 500, 60, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Widget)
        self.label_13.setGeometry(QtCore.QRect(220, 500, 60, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Widget)
        self.label_14.setGeometry(QtCore.QRect(415, 500, 60, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Widget)
        self.label_15.setGeometry(QtCore.QRect(350, 500, 60, 16))
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Widget)
        self.label_16.setGeometry(QtCore.QRect(480, 500, 60, 16))
        self.label_16.setObjectName("label_16")
        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)
    
    
    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label.setText(_translate("Widget", "1"))
        self.label_2.setText(_translate("Widget", "2"))
        self.label_3.setText(_translate("Widget", "3"))
        self.label_4.setText(_translate("Widget", "4"))
        self.label_5.setText(_translate("Widget", "5"))
        self.label_6.setText(_translate("Widget", "7"))
        self.label_7.setText(_translate("Widget", "6"))
        self.label_8.setText(_translate("Widget", "8"))
        self.label_9.setText(_translate("Widget", "1"))
        self.label_10.setText(_translate("Widget", "4"))
        self.label_11.setText(_translate("Widget", "2"))
        self.label_12.setText(_translate("Widget", "8"))
        self.label_13.setText(_translate("Widget", "3"))
        self.label_14.setText(_translate("Widget", "6"))
        self.label_15.setText(_translate("Widget", "5"))
        self.label_16.setText(_translate("Widget", "7"))
        

